# config.yaml

## Where the samples will be written
save_data: Data/run2/example
## Where the vocab(s) will be written
src_vocab: Data/run2/example.vocab.src
tgt_vocab: Data/run2/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: Data/src-train.txt
        path_tgt: Data/tgt-train.txt
    valid:
        path_src: Data/src-val.txt
        path_tgt: Data/tgt-val.txt

# Vocabulary files that were just created
src_vocab: Data/run2/example.vocab.src
tgt_vocab: Data/run2/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: Data/run1/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500